Added coveralls CI step

diff --git a/.github/workflows/build-linux.yaml b/.github/workflows/build-linux.yaml
--- a/.github/workflows/build-linux.yaml
+++ b/.github/workflows/build-linux.yaml
@@ -60,15 +60,24 @@ jobs:
             setapikey "${{ secrets.GH_PACKAGES_TOKEN }}" \
             -Source "${{ env.FEED_URL }}"
 
-      - name: Generate and Configure Debug
-        run: cmake . --preset=Debug -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake
+      - name: Generate and Configure Debug-Coverage
+        run: cmake . --preset=Debug-Coverage -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake
 
-      - name: Build Debug
-        run: cmake --build build/Debug
+      - name: Build Debug-Coverage
+        run: cmake --build build/Debug-Coverage
 
       - name: Test Debug
         run: ctest --output-junit test_detail_debug.xml --output-on-failure
-        working-directory: ./build/Debug/
+        working-directory: ./build/Debug-Coverage/
+
+      - name: Prepare Python for Coverage Upload
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.13'
+      - name: Upload Coverage to Coveralls
+        run: |
+            python -m pip install --user cpp-coveralls==0.4.2
+            coveralls --exclude tests/ --exclude external/ --root . --build-root ./build/Debug-Coverage/ --gcov-options '\-lp' || echo "Coverage upload failed"
 
       - name: Generate and Configure Release
         run: cmake . --preset=Release -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake
