Try to get test to pass in CI

diff --git a/.github/workflows/build-linux.yaml b/.github/workflows/build-linux.yaml
--- a/.github/workflows/build-linux.yaml
+++ b/.github/workflows/build-linux.yaml
@@ -49,7 +49,8 @@ jobs:
       - name: Build Debug-Coverage
         run: cmake --build build/Debug-Coverage
 
-      - name: Test Debug
+      - name: Test Debug-Coverage
+        id: test-debug-coverage
         working-directory: build/Debug-Coverage
         run: ctest --output-junit test_detail_debug.xml --output-on-failure
         continue-on-error: true
@@ -67,6 +68,12 @@ jobs:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           path-to-lcov: ./build/Debug-Coverage/lcov.info
         continue-on-error: true
+
+      - name: Check Test Failure
+        if: ${{ steps.test-debug-coverage.conclusion == 'failure' }}
+        run: |
+          echo "Tests Failed check logs"
+          exit 1
 
   build_and_test_release:
     name: Build and Test (Linux/Release)
